### ISSUE TITLE
Notification Panel throws errors under ng2 (official release)

### ISSUE THREAD

**Issue by cdarrigo** [sstorie/experiments#10]
Assigning animation triggers via @prop="exp" attributes with an expression is invalid. Use property bindings (e.g. [@prop]="exp") or use an attribute without a value (e.g. @prop) instead. ("<div class="container" [ERROR ->]@panelWidthTrigger="expandedState">
  <div class="title" @titleColorTrigger="expandedState">
    <s"):

**Comment by sstorie** [comment]
Thanks for submitting the issue @cdarrigo. I will try to make some time to update the code and examples to the current release of Angular 2. I didn't realize how out-of-date it was until I started looking into what you found...!

**Comment by jhillhouse92** [comment]
@sstorie any update on this? I'm still experiencing these issues.

**Comment by jhillhouse92** [comment]
:sadpanda:

**Comment by jhillhouse92** [comment]
@sstorie if you are good with pull request, the animated notifications panel can be updated to work.

**Comment by sstorie** [comment]
Absolutely. Thanks for doing that.
