### ISSUE TITLE
Uncaught Error: The variable '$' or the .hubConnection() function are not defined...please check the SignalR scripts have been loaded properly

### ISSUE THREAD

**Issue by lhaisrs** [sstorie/experiments#12]
How can I resolve this error?

**Comment by sstorie** [comment]
You need to ensure the SinglarR scripts are loaded into the page before any of your Angular code is. Can you post your page's HTML that shows the script tags loaded?

**Comment by sstorie** [comment]
Closing since no new information has been provided.
