### ISSUE TITLE
Async Issue

### ISSUE THREAD

**Issue by jezmaghuyop** [sstorie/experiments#17]
Hi, I've been trying to make the connectionState but it doesn't reflect on the Template

```
this.connectionState$ = this.channelService.connectionState$
.map((state: ConnectionState) => { return ConnectionState[state]; });

<div>
    <span>Connection state: {{connectionState$ | async}}</span>
</div>

I can check that the connectionState$ changed from console.log but in the template view it's not changing, but when I clicked on a Button that does nothing just a normal button the connectionState$ suddenly shows up.

<button (click)="sample()">Click Me</button>

inside my component
public sample() {
 //nothing in here
}

**Comment by sstorie** [comment]
This sounds like an issue with zones. Somehow the changes in connection state aren't being handled withing a zone, so it takes another event (like a button click) to trigger Angular to detect changes. Try wrapping your code (or even the code in my example if it's not there already) with a call like the following:

```typescript
this.zone.run(() => { ...your code here...});
```

In that snippet I'm assuming you've injected a property called `zone` of type `NgZone` into your service or component. That should trigger Angular to detect changes when your code completes, and the UI will update like you expect.

**Comment by jezmaghuyop** [comment]
Should I put NgZone in Service or in my Component? sorry I'm really new to Angular2 and SignalR

**Comment by sstorie** [comment]
For something like this I typically put then in a shared service. Otherwise every component that used the "async" value would need to so the zone stuff themselves...leading to a lot of repeated code.

**Comment by jezmaghuyop** [comment]
This is what my service looks like, not sure where to put it, I'm only having issue with the ConnectionState everything else seems to work fine, but I have to check again after I fix the issue with connectionState

```
    constructor() {
        //debugger;        

        // Set up our observables        
        this.connectionState$ = this.connectionStateSubject.asObservable();
        this.starting$ = this.startingSubject.asObservable();
        this.error$ = this.errorSubject.asObservable();

        //Configure Hub Connection 
        this.setupHub();     
    }

    private setupHub() {

        // create hub connection  
        this.connection = $.hubConnection('http://localhost:63690');
        // create new proxy as name already given in top  
        this.hub = this.connection.createHubProxy(this.hubName);

        // Define handlers for the connection state events        
        this.connection.stateChanged((state: any) => {
            let newState = ConnectionState.Connecting;
            
            switch (state.newState) {
                case $.signalR.connectionState.connecting:
                    newState = ConnectionState.Connecting;
                    break;
                case $.signalR.connectionState.connected:
                    newState = ConnectionState.Connected;
                    break;
                case $.signalR.connectionState.reconnecting:
                    newState = ConnectionState.Reconnecting;
                    break;
                case $.signalR.connectionState.disconnected:
                    newState = ConnectionState.Disconnected;
                    break;
            }
                        
            // Push the new state on our subject                        
            this.connectionStateSubject.next(newState);
        });

        // Define handlers for any errors        
        this.connection.error((error: any) => {
            // Push the error on our subject            
            this.errorSubject.next(error);
        });

        this.startConnection();
        
    }


```

**Comment by sstorie** [comment]
Try something like this:

```typescript
import {NgZone} from "@angular/core";

constructor(private zone: NgZone) {
        //debugger;        

        // Set up our observables        
        this.connectionState$ = this.connectionStateSubject.asObservable();
        this.starting$ = this.startingSubject.asObservable();
        this.error$ = this.errorSubject.asObservable();

        //Configure Hub Connection 
        this.setupHub();     
    }

    private setupHub() {

        // create hub connection  
        this.connection = $.hubConnection('http://localhost:63690');
        // create new proxy as name already given in top  
        this.hub = this.connection.createHubProxy(this.hubName);

        // Define handlers for the connection state events        
        this.connection.stateChanged((state: any) => {
            let newState = ConnectionState.Connecting;
            
            switch (state.newState) {
                case $.signalR.connectionState.connecting:
                    newState = ConnectionState.Connecting;
                    break;
                case $.signalR.connectionState.connected:
                    newState = ConnectionState.Connected;
                    break;
                case $.signalR.connectionState.reconnecting:
                    newState = ConnectionState.Reconnecting;
                    break;
                case $.signalR.connectionState.disconnected:
                    newState = ConnectionState.Disconnected;
                    break;
            }
                        
            // Push the new state on our subject within a zone
           this.zone.run(() => {                        
            this.connectionStateSubject.next(newState);
           });
        });

        // Define handlers for any errors        
        this.connection.error((error: any) => {
            // Push the error on our subject within a zone
           this.zone.run(() => {                                    
            this.errorSubject.next(error);
           });
        });

        this.startConnection();
        
    }
```

**Comment by jezmaghuyop** [comment]
Hmmmm, not sure why having ngZone in the constructor causes an error

```
constructor(private zone: NgZone) {
  code goes here
}
```

Error in console
Error: Can't resolve all parameters for ChatService: (?). at SyntaxError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:6895:33) at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:64681:16) at new SyntaxError (http://localhost:4200/vendor.bundle.js:5723:16) at CompileMetadataResolver._getDependenciesMetadata (http://localhost:4200/vendor.bundle.js:16897:31) at CompileMetadataResolver._getTypeMetadata (http://localhost:4200/vendor.bundle.js:16772:26) at CompileMetadataResolver._getInjectableMetadata (http://localhost:4200/vendor.bundle.js:16760:21) at CompileMetadataResolver.getProviderMetadata (http://localhost:4200/vendor.bundle.js:17002:40) at http://localhost:4200/vendor.bundle.js:16960:49 at Array.forEach (native) at CompileMetadataResolver._getProvidersMetadata (http://localhost:4200/vendor.bundle.js:16927:19) at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:16611:50) at JitCompiler._loadModules (http://localhost:4200/vendor.bundle.js:47728:64) at JitCompiler._compileModuleAndComponents (http://localhost:4200/vendor.bundle.js:47688:52) at JitCompiler.compileModuleAsync (http://localhost:4200/vendor.bundle.js:47654:21) at PlatformRef_._bootstrapModuleWithZone (http://localhost:4200/vendor.bundle.js:36436:25)

**Comment by jezmaghuyop** [comment]
Sorry my bad, it has something to do with the @Injectable being on top of other Export Class instead of the  ChatService. Your code suggestion works 100% well. Thank you so much!
