### ISSUE TITLE
service register issue angular2 rc5  { provide: 'channel.config', useValue: channelConfig },

### ISSUE THREAD

**Issue by amjadDev** [sstorie/experiments#20]
ERROR in Error encountered resolving symbol values statically. Calling function
'ChannelConfig', function calls are not supported. Consider replacing the functi
on or lambda with a reference to an exported function, resolving symbol AppModul
e in  mypth/src/app/app.module.ts, resolving
 symbol AppModule in mypth/app/app.modu
le.ts

**Comment by sstorie** [comment]
Closing since no new information has been provided.
