### ISSUE TITLE
angular2-animated-notifications-panel doesn't work in Firefox

### ISSUE THREAD

**Issue by thardes2** [sstorie/experiments#5]
Getting the exception:

> EXCEPTION: Error in http://localhost:3000/app/notification/notification.component.html:0:18"platform-browser.umd.js:1900:17
> ORIGINAL EXCEPTION: TypeError: Invalid easing 'null'.

in Firefox. Chrome works fine.

Next thing: 
If I click the "toggle-button" in firefox, the action is executed in Chrome

**Comment by sstorie** [comment]
Yeah, that is certainly due to the fact I don't use Firefox on a daily basis (or IE for that matter). I don't know how much time I'll have to try to fix this, but I'll add a quick note to the article to make it clear I only used Chrome while building the experiment.

**Comment by sstorie** [comment]
Closing since this is quite old now
