### ISSUE TITLE
How about prefetching data from one of the services ?

### ISSUE THREAD

**Issue by happyvig** [sstorie/experiments#6]
Hi.,

What changes would it need to call one of the application services method and bootstrap the same service with the response data on successful response ?

**Comment by sstorie** [comment]
Can you be a little more specific on what experiment this is related to? I don't quite understand from the question.

**Comment by happyvig** [comment]
Say for example : 

There is an Angular 2 app with few services like LoggerService, HttpService, DiscoveryService., etc.

step 1: Call DiscoveryService's 'getApis' ( which will make a http call to a server to get the result ) method, which will store a copy of the array of api names inside itself before actually returning them.
step 2: Now do the actual bootstrap of the app, passing in all the providers,services ( including the same DiscoveryService so that the components can use stores api names ), etc  only on successful response

**Comment by sstorie** [comment]
I don't think what you're describing is possible with a single Angular app, or to be more careful, I don't know how to achieve that. To leverage the components/services in your Angular app you need to bootstrap the app, so if you're trying to provide data to the bootstrap call it needs to come from somewhere else. That something else could be a few different things:

- Data rendered on the server and provided with the angular app itself
- Data fetched from a remote API via some client-side mechanism outside of your Angular app (say via jquery or something)
- Perhaps even a second Angular app...but that would be something to explore before knowing if it's possible

If you come across another way to handle this please let me know!

**Comment by happyvig** [comment]
Thanks.
